from abc import ABC, abstractmethod
from typing import Dict, Any, List

class BaseLLM(ABC):
    """
    Abstract base class for all LLM APIs.
    Provides a unified interface for calling different LLM providers.
    """

    def __init__(self, model_name: str, api_key: str, **kwargs):
        """
        Initialize the LLM API wrapper.

        Args:
            model_name (str): Name of the model to use.
            api_key (str): API key for authentication.
            **kwargs: Additional model-specific parameters (e.g., temperature, top_p).
        """
        self.model_name = model_name
        self.api_key = api_key
        self.model_kwargs = kwargs
        # Token statistics
        self.total_tokens = 0
        self.prompt_tokens = 0
        self.completion_tokens = 0
        self.api_calls = 0

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate a single text completion for the given prompt.

        Args:
            prompt (str): Input prompt for the model.
            **kwargs: Provider-specific override parameters.

        Returns:
            str: Text generated by the model.
        """
        pass

    def batch_generate(self, prompts: List[str], **kwargs) -> List[str]:
        """
        Generate text completions for a batch of prompts.
        Subclasses should implement this method if the provider supports efficient batching.
        Otherwise, it defaults to iteratively calling `generate`.
        """
        return [self.generate(prompt, **kwargs) for prompt in prompts]

    def __call__(self, prompt: str, **kwargs) -> str:
        """
        Allow calling the object as a function.
        """
        return self.generate(prompt, **kwargs)

    def get_token_stats(self) -> Dict[str, int]:
        """Get token statistics"""
        return {
            "total_tokens": self.total_tokens,
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
            "api_calls": self.api_calls
        }

    def reset_token_stats(self):
        """Reset token statistics"""
        self.total_tokens = 0
        self.prompt_tokens = 0
        self.completion_tokens = 0
        self.api_calls = 0